
networks:
  edcl-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.7.0.0/16
          gateway: "${GATEWAY}"

services:
  postgres:
    image: postgres:15
    mem_limit: 1024m
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
      - /home/emer/Documents/Postgres:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - edcl-network

  exchange-rate:
    image: exchange-rate:7.0.0
    mem_limit: 1024m
    restart: always
    ports:
      - "8008:8008"
    environment:
      POSTGRES_URL: "${POSTGRES_URL}"
      API_KEY: "${API_KEY}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      URL: "${URL}"
    volumes:
      - /home/emer/Documents/KotlinLogs:/home/emer/Documents/KotlinLogs
    depends_on:
      - postgres
    networks:
      - edcl-network

  angular-exchange:
    image: angular-exchange:6.0.0
    ports:
      - "4200:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - exchange-rate
    restart: always
    networks:
      - edcl-network

