
version: '2.4'


services:
  postgres:
    image: postgres:15
    mem_limit: 1024m
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
      - /home/emerson/Documentos/Postgres:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  exchange-rate:
    image: exchange-rate:2.0.0
    mem_limit: 1024m
    restart: always
    ports:
      - "8080:8080"
    environment:
      POSTGRES_URL: "${POSTGRES_URL}"
      API_KEY: "${API_KEY}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      URL: "${URL}"
    depends_on:
      - postgres