api:
  key: ${API_KEY:Vbb6s2cv4bOnsoaKUrNBqnpkwFVcEwsD}
  url: ${URL:https://api.apilayer.com/exchangerates_data/convert}

server:
  port: 8008

spring:
  datasource:
    type: org.postgresql.jdbc2.optional.SimpleDataSource
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/software}
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: exchange-rate

keycloak:
  auth-server-url: ${KEYCLOAK_URL:http://localhost:8080}
  autodetect-bearer-only: true
  realm: software
  ssl-required: none
  resource: backend
  credentials:
    secret: hqxXhNfuvAPZCjOkLR4QagUzwZbBGxFT
  use-resource-role-mappings: false
  security-constraints:
    - auth-roles:
        - user
      security-collections:
        - name: SERVICIOS DE USUARIO
          omitted-methods:
            - OPTIONS
          patterns:
            - /api/v1/exchange/get
    - auth-roles:
        - admin
      security-collections:
        - name: SERVICIOS DE ADMINISTRADOR
          omitted-methods:
            - OPTIONS
          patterns:
            - /api/v1/exchange/getall