api:
  key: ${API_KEY}
  url: ${URL:https://api.apilayer.com/exchangerates_data/convert}

server:
  port: 8080

spring:
  datasource:
    type: org.postgresql.jdbc2.optional.SimpleDataSource
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD}
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/postgres}
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: exchange-rate


